apiVersion: v2
name: myapp
description: A Helm chart for Kubernetes deployment via Jenkins
type: application
version: 1.0.0
appVersion: 1.0.0

dependencies:
  - name: postgresql
    version: ~12.1.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled